SELECT * FROM PAYMENT WHERE TYPE_ID = 4;
SELECT * FROM MARK WHERE SUBJECT_ID = 92;
SELECT * FROM STUDENT
    INNER JOIN PAYMENT ON STUDENT.ID = PAYMENT.STUDENT_ID
 WHERE PAYMENT.TYPE_ID =2;
SELECT * FROM STUDENT
    INNER JOIN MARK ON STUDENT.ID = MARK.STUDENT_ID
    WHERE MARK.SUBJECT_ID = 104;

