SELECT mark
FROM Mark
WHERE mark > 6
ORDER BY mark DESC;

SELECT * FROM PAYMENT WHERE AMOUNT < 300 ORDER BY AMOUNT;
SELECT * FROM PAYMENTTYPE ORDER BY NAME ASC;
SELECT * FROM STUDENT ORDER BY NAME DESC;
SELECT * FROM STUDENT
    INNER JOIN PAYMENT ON STUDENT.ID = PAYMENT.STUDENT_ID
         GROUP BY PAYMENT.STUDENT_ID, STUDENT.ID, PAYMENT.ID
         HAVING AMOUNT >1000 ORDER BY BIRTHDAY ASC;