SELECT *
FROM Mark
WHERE mark > 6
ORDER BY mark DESC;

SELECT * FROM PAYMENT WHERE AMOUNT < 300 ORDER BY AMOUNT ASC;
SELECT * FROM PAYMENTTYPE ORDER BY NAME ASC;
SELECT * FROM STUDENT ORDER BY NAME DESC;
SELECT * FROM STUDENT
    INNER JOIN PAYMENT ON STUDENT.ID = PAYMENT.STUDENT_ID
         where AMOUNT >1000 ORDER BY STUDENT.BIRTHDAY ASC;