ALTER TABLE student MODIFY birthday DATE NOT NULL;
ALTER TABLE mark MODIFY mark INT NOT NULL CHECK (mark BETWEEN 1 AND 10);
ALTER TABLE mark  ADD CONSTRAINT fk_student_id FOREIGN KEY (student_id) REFERENCES student (id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE mark ADD CONSTRAINT fk_subject_id FOREIGN KEY (subject_id) REFERENCES subject (id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE subject MODIFY grade INT NOT NULL CHECK (grade BETWEEN 1 AND 5);
ALTER TABLE paymenttype  MODIFY name VARCHAR(45) UNIQUE;
ALTER TABLE payment MODIFY type_id BIGINT NOT NULL;
ALTER TABLE payment MODIFY amount decimal NOT NULL;
ALTER TABLE payment MODIFY payment_date DateTime NOT NULL;
ALTER TABLE payment ADD CONSTRAINT fk_type_id FOREIGN KEY (type_id) REFERENCES paymenttype (id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE payment ADD CONSTRAINT fk_student_id FOREIGN KEY (student_id) REFERENCES student (id) ON DELETE CASCADE ON UPDATE CASCADE;

